### ISSUE TITLE
How did u create bent normal maps?

### ISSUE THREAD

**Issue by MikeKotys** [keijiro/BentNormalTest#1]
This is not an issue, but I could not find any way to contact u. I tried making bent normal maps with Substance Designer but this did not produce good looking results so I wanted to ask how u did it?

**Comment by keijiro** [comment]
I can't remember how I created them (it was three years ago!), but I guess it might be xNormal or Knald because I have never used other tools.

https://xnormal.net/

https://www.knaldtech.com/knald/

**Comment by MikeKotys** [comment]
Hey, ty for the answer - will definitely check them!

пн, 15 февр. 2021 г. в 11:30, Keijiro Takahashi <notifications@github.com>:
